---
-   hosts: "teamcity"
    become: true
    gather_facts: false
    vars_files:
        - group_vars/vault.yml
        - group_vars/vars.yml

    tasks:
        -   name: "Packages"
            include_tasks: "tasks/packages.yml"

        -   name: "Docker"
            include_tasks: "tasks/docker.yml"

        -   name: "Firewall"
            include_tasks: "tasks/firewall.yml"

        -   name: "POSTGRESQL"
            include_tasks: "tasks/postgresql.yml"

        -   name: Copy scripts
            template:
                src: "templates/{{ item }}.sh"
                dest: "/home/{{host_user}}/{{ item }}.sh"
                owner: "{{host_user}}"
                group: "{{host_user}}"
                mode: '0755'
            loop: [ 'deploy', 'server', 'agent', 'proxy' ]

#        -   name: "Copy files for agent"
#            become: true
#            copy:
#                src: "templates/agent"
#                dest: "/home/{{host_user}}"
#                owner: "{{host_user}}"
#                group: "{{host_user}}"
#                mode: 'u=rwx,g=r,o=r'
#            tags: ['copy_files']
#
#        -   name: "Copy files for server"
#            become: true
#            copy:
#                src: "templates/server"
#                dest: "/home/{{host_user}}"
#                owner: "{{host_user}}"
#                group: "{{host_user}}"
#                mode: 'u=rwx,g=r,o=r'
#            tags: ['copy_files']

        -   name: "Copy directories for server and agent"
            become: true
            copy:
                src: "templates/{{item}}"
                dest: "/home/{{host_user}}"
                owner: "{{host_user}}"
                group: "{{host_user}}"
                mode: 'u=rwx,g=r,o=r'
            loop:
                - "server-files"
                - "agent-files"
            tags: ['copy_files']


        -   name: "Container Proxy"
            include_tasks: "tasks/container-proxy.yml"

    handlers:
        -   name: "restart sshd"
            become: true
            service: name=sshd state=restarted
