---
-   hosts: "teamcity"
    become: true
    gather_facts: false
    vars_files:
        - group_vars/vault.yml
        - group_vars/vars.yml

    tasks:

        - name: "Copy docker-compose"
          template:
              src: templates/docker-compose.yml
              dest: "/home/{{host_user}}/docker-compose.yml"
              owner: "{{host_user}}"
              group: "{{host_user}}"
              mode: '0755'
          tags: [ 'docker-compose' ]

        -   name: "Copy template for strapi config"
            become: true
            template:
                src: "templates-strapi/config/{{item}}"
                dest: "/home/{{host_user}}/strapi/config/{{item}}"
                owner: "{{host_user}}"
                group: "{{host_user}}"
                mode: 'u=rwx,g=r,o=r'
            loop:
                - "admin.js"
                - "database.js"
                - "plugins.js"
                - "server.js"
            tags: ['copy_files']

        - name: "Copy entrypoint.sh for strapi"
          template:
              src: templates-strapi/{{item}}
              dest: "/home/{{host_user}}/strapi/{{item}}"
              owner: "{{host_user}}"
              group: "{{host_user}}"
              mode: '0755'
          loop:
              - "entrypoint.sh"
              - "package.json"
              - "yarn.lock"

        -   name: "Copy template for servers"
            become: true
            template:
                src: "templates-pgadmin/{{item}}"
                dest: "/home/{{host_user}}/pgadmin/{{item}}"
                owner: "{{host_user}}"
                group: "{{host_user}}"
                mode: 'u=rwx,g=r,o=r'
            loop:
                - "servers.json"
            tags: ['copy_files']

        -   name: "Copy proxy nginx.conf"
            copy:
                src: templates/proxy/nginx/nginx.conf
                dest: "/home/{{host_user}}/proxy/nginx/nginx.conf"

    handlers:
        -   name: "restart sshd"
            become: true
            service: name=sshd state=restarted
