# FIREWALL
-   debug:
        msg: 🧱 TASK FIREWALL

# https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html

# UFW Configuration
-   name: "UFW - Deny everything and enable UFW"
    community.general.ufw:
        state: enabled
        policy: deny

-   name: "UFW - Allow HTTP on port 80"
    ufw:
        rule: allow
        port: "80"
        proto: tcp

-   name: "UFW - Allow 8080 on port 80"
    ufw:
        rule: deny
        port: "8080"
        proto: tcp

-   name: "UFW - Allow HTTPS on port 443"
    ufw:
        rule: allow
        port: "443"
        proto: tcp

-   name: "UFW - Allow SSH on port 22"
    ufw:
        rule: allow
        port: "22"
        proto: tcp

-   name: "UFW - Protect ssh against brute force attack"
    ufw:
        rule: limit
        port: ssh
        proto: tcp
