# STRAPI
-   debug:
      msg: 🚧 STRAPI

- name: Create a directory if it does not exist
  file:
        path: /home/{{host_user}}/strapi
        owner: "{{host_user}}"
        group: "{{host_user}}"
        state: directory
        mode: '0755'

- name: Create a directory if it does not exist
  file:
        path: /home/{{host_user}}/strapi/config
        state: directory
        mode: '0755'

- name: Create a directory if it does not exist
  file:
        path: /home/{{host_user}}/strapi/secrets
        state: directory
        mode: '0755'

- name: Create a directory if it does not exist
  file:
        path: /home/{{host_user}}/strapi/src
        state: directory
        mode: '0755'

- name: Create a directory if it does not exist
  file:
        path: /home/{{host_user}}/strapi/public/uploads
        state: directory
        mode: '0755'

- name: "Copy .env for strapi"
  template:
        src: templates-strapi/.env
        dest: "/home/{{host_user}}/strapi/.env"
        owner: "{{host_user}}"
        group: "{{host_user}}"
        mode: '0755'

- name: "Copy entrypoint.sh for strapi"
  template:
        src: templates-strapi/entrypoint.sh
        dest: "/home/{{host_user}}/strapi/entrypoint.sh"
        owner: "{{host_user}}"
        group: "{{host_user}}"
        mode: '0755'

-   name: "Copy directories for config"
    become: true
    copy:
          src: "templates-strapi/{{item}}"
          dest: "/home/{{host_user}}"
          owner: "{{host_user}}"
          group: "{{host_user}}"
          mode: 'u=rwx,g=r,o=r'
    loop:
          - "config"
    tags: ['copy-files']

#-   name: "Copy secrets"
#    template:
#      src: "templates-strapi/secrets/{{ item }}"
#      dest: "/home/{{host_user}}/secrets/{{ item | basename | regex_replace('\\.txt', '') }}"
#    with_fileglob:
#      - "./templates-strapi/secrets/*.txt"
#    tags: ['copy-files']

-   name: "Copy secrets"
    template:
      src: "{{ item.path }}"
      dest: "{{ target_dir }}/{{ item.path }}"
    with_community.general.filetree:
      path: "templates-strapi/secrets"
    vars:
      target_dir: "/home/{{host_user}}/strapi/secrets"
