# CONTAINER PROXY
-   debug:
        msg: 🐳 TASK CONTAINER PROXY

-   name: "Create proxy directories"
    file:
        path: "{{item}}"
        state: directory
    loop:
        - "/home/{{host_user}}/proxy/nginx"

-   name: "Copy proxy nginx.conf"
    copy:
        src: templates/proxy/nginx/nginx.conf
        dest: "/home/{{host_user}}/proxy/nginx/nginx.conf"

-   name: "Copy proxy certs"
    copy:
        src: templates/proxy/certs
        dest: "/home/{{host_user}}/proxy"

-   name: "Copy proxy conf.d"
    copy:
        src: templates/proxy/nginx/conf.d
        dest: "/home/{{host_user}}/proxy/nginx"

-   name: "Copy proxy sites-enabled"
    copy:
        src: templates/proxy/nginx/sites-enabled
        dest: "/home/{{host_user}}/proxy/nginx"

-   name: "Copy default proxy index.html"
    copy:
        src: templates/proxy/html
        dest: "/var/www"
