version: '3.4'
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    restart: always
    volumes:
      - /home/{{host_user}}/proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/{{host_user}}/proxy/nginx/conf.d:/etc/nginx/conf.d
      - /home/{{host_user}}/proxy/nginx/sites-enabled:/etc/nginx/sites-enabled
      - /var/www/html:/usr/share/nginx/html
      - /var/log/nginx:/var/log/nginx
      - /home/{{host_user}}/proxy/certs/{{project}}/public.key:/etc/ssl/certs/public.key
      - /home/{{host_user}}/proxy/certs/{{project}}/private.key:/etc/ssl/private/private.key
    ports:
      - "80:80"
      - "443:443"
    networks:
      teamcity:
        ipv4_address: 192.168.176.80
  server:
    container_name: server
    image: jetbrains/teamcity-server:2023.11.4
    restart: always
    environment:
      TEAMCITY_SERVER_MEM_OPTS: "-Xmx2048m" # Limit memory usage
    ports:
      - "8111:8111"
    networks:
      teamcity:
        ipv4_address: 192.168.176.81
    volumes:
      - volume_server_data:/data/teamcity_server/datadir
      - volume_server_logs:/opt/teamcity/logs
      - /home/{{host_user}}/server-files/server.xml:/opt/teamcity/conf/server.xml
      - /home/{{host_user}}/server-files/server.database.properties:/data/teamcity_server/datadir/config/database.properties
  agent_zero:
    container_name: agent_zero
    restart: always
    build:
      context: /home/{{host_user}}/agent-files
      dockerfile: agent.zero.Dockerfile
      network: host
    networks:
      teamcity:
        ipv4_address: 192.168.176.60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/{{host_user}}/agent-files:/home/buildagent/agent-files
    environment:
      SERVER_URL: http://server:8111
      AGENT_NAME: agent_zero
      DOCKER_IN_DOCKER: start
    privileged: true
    user: root
  agent_one:
    container_name: agent_one
    restart: always
    build:
      context: /home/{{host_user}}/agent-files
      dockerfile: agent.zero.Dockerfile
      network: host
    networks:
      teamcity:
        ipv4_address: 192.168.176.61
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/{{host_user}}/agent-files:/home/buildagent/agent-files
    environment:
      SERVER_URL: http://server:8111
      AGENT_NAME: agent_one
      DOCKER_IN_DOCKER: start
    privileged: true
    user: root
  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8089:8080"
    volumes:
      - /home/{{host_user}}/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      pgadmin:
        ipv4_address: 192.168.133.33
  strapi:
    image: elestio/strapi-${NODE_ENV}:latest
    restart: always
    env_file: strapi/.env
    environment:
      DATABASE_CLIENT: postgres
      NODE_ENV: production
      ADMIN_PASSWORD: run/secrets/strapi_admin_password
      ADMIN_EMAIL: run/secrets/strapi_admin_email
      BASE_URL: run/secrets/strapi_base_url
      SMTP_HOST: run/secrets/strapi_smtp_host
      SMTP_PORT: run/secrets/strapi_smtp_port
      SMTP_AUTH_STRATEGY: run/secrets/strapi_smtp_auth_strategy
      SMTP_FROM_EMAIL: run/secrets/strapi_smtp_from_email
      DATABASE_USERNAME: run/secrets/strapi_database_username
      DATABASE_PASSWORD: run/secrets/strapi_database_password
      DATABASE_HOST: run/secrets/strapi_database_host
      DATABASE_PORT: run/secrets/strapi_database_port
      DATABASE_NAME: run/secrets/strapi_database_name
      JWT_SECRET: run/secrets/strapi_jwt_secret
      ADMIN_JWT_SECRET: run/secrets/strapi_admin_jwt_secret
      APP_KEYS: run/secrets/strapi_app_keys
      API_TOKEN_SALT: run/secrets/strapi_api_token_salt
      TRANSFER_TOKEN_SALT: run/secrets/strapi_transfer_token_salt
    secrets:
      - strapi_admin_password
      - strapi_admin_email
      - strapi_base_url
      - strapi_smtp_host
      - strapi_smtp_port
      - strapi_smtp_auth_strategy
      - strapi_smtp_from_email
      - strapi_database_username
      - strapi_database_password
      - strapi_database_host
      - strapi_database_port
      - strapi_database_name
      - strapi_jwt_secret
      - strapi_admin_jwt_secret
      - strapi_app_keys
      - strapi_api_token_salt
      - strapi_transfer_token_salt
    volumes:
      - /home/{{host_user}}/strapi/config:/opt/app/config
      - /home/{{host_user}}/strapi/src:/opt/app/src
      # - /home/{{host_user}}/strapi/package.json:/opt/package.json
      # - /home/{{host_user}}/strapi/yarn.lock:/opt/yarn.lock
      - /home/{{host_user}}/strapi/.env:/opt/app/.env
      - /home/{{host_user}}/strapi/public/uploads:/opt/app/public/uploads
      - /home/{{host_user}}/strapi/entrypoint.sh:/opt/app/entrypoint.sh
    ports:
      - "9930:1337"
    networks:
      strapi:
        ipv4_address: 192.168.220.22
networks:
  teamcity:
    ipam:
      driver: default
      config:
        - subnet: "192.168.176.0/20"
  strapi:
    ipam:
      driver: default
      config:
        - subnet: "192.168.220.0/20"
  pgadmin:
    ipam:
      driver: default
      config:
        - subnet: "192.168.133.0/20"
secrets:
  strapi_admin_password:
    file: strapi/secrets/strapi_admin_password.txt
  strapi_admin_email:
    file: strapi/secrets/strapi_admin_email.txt
  strapi_base_url:
    file: strapi/secrets/strapi_base_url.txt
  strapi_smtp_host:
    file: strapi/secrets/strapi_smtp_host.txt
  strapi_smtp_port:
    file: strapi/secrets/strapi_smtp_port.txt
  strapi_smtp_auth_strategy:
    file: strapi/secrets/strapi_smtp_auth_strategy.txt
  strapi_smtp_from_email:
    file: strapi/secrets/strapi_smtp_from_email.txt
  strapi_database_username:
    file: strapi/secrets/strapi_database_username.txt
  strapi_database_password:
    file: strapi/secrets/strapi_database_password.txt
  strapi_database_host:
    file: strapi/secrets/strapi_database_host.txt
  strapi_database_port:
    file: strapi/secrets/strapi_database_port.txt
  strapi_database_name:
    file: strapi/secrets/strapi_database_name.txt
  strapi_jwt_secret:
    file: strapi/secrets/strapi_jwt_secret.txt
  strapi_admin_jwt_secret:
    file: strapi/secrets/strapi_admin_jwt_secret.txt
  strapi_app_keys:
    file: strapi/secrets/strapi_app_keys.txt
  strapi_api_token_salt:
    file: strapi/secrets/strapi_api_token_salt.txt
  strapi_transfer_token_salt:
    file: strapi/secrets/strapi_transfer_token_salt.txt
volumes:
  volume_server_data:
    external: true
  volume_server_logs:
    external: true
  volume_agent:
    external: true
#  volume_postgresql:
#    external: true
